services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: iam_ops_backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    environment:
      FRONTEND_URL: http://localhost:3000
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: iam_ops_frontend
    restart: unless-stopped
    environment:
      NEXT_PUBLIC_API_BASE_URL: http://localhost:8000
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
